# Generated by Django 4.2.30 on 2026-09-02 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0002_categorias_iniciais'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemSolicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Mensagem')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_solicitacao', to=settings.AUTH_USER_MODEL)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='services.solicitacaoservico')),
            ],
            options={
                'verbose_name': 'Mensagem da solicitação',
                'verbose_name_plural': 'Mensagens das solicitações',
                'ordering': ['criada_em'],
            },
        ),
    ]
