# Generated by Django 4.2.30 on 2026-09-02 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_mensagemsolicitacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagemsolicitacao',
            name='lida',
            field=models.BooleanField(default=False),
        ),
    ]
