# Generated by Django 4.2.30 on 2026-09-16 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_servico_subservico_e_observacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoservico',
            name='data_visita',
            field=models.DateField(blank=True, help_text='Dia escolhido pelo cliente, no calendário, para a visita do profissional.', null=True, verbose_name='Dia da visita solicitado'),
        ),
    ]
