# Generated by Django 4.2.30 on 2026-09-16 23:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_solicitacaoservico_data_visita'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor do orçamento (R$)')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações para o cliente')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('solicitacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orcamento', to='services.solicitacaoservico')),
            ],
            options={
                'verbose_name': 'Orçamento',
                'verbose_name_plural': 'Orçamentos',
            },
        ),
        migrations.CreateModel(
            name='DiaVisitaOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Dia da visita')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias_visita', to='services.orcamento')),
            ],
            options={
                'verbose_name': 'Dia de visita do orçamento',
                'verbose_name_plural': 'Dias de visita do orçamento',
                'ordering': ['data'],
            },
        ),
    ]
