# Generated by Django 4.2.30 on 2026-09-16 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_orcamento_diavisitaorcamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoservico',
            name='visita_concluida_em',
            field=models.DateTimeField(blank=True, help_text='Preenchido quando o cliente confirma que o profissional foi até a casa dele, liberando a aba Orçamentos para essa solicitação.', null=True, verbose_name='Visita concluída em'),
        ),
    ]
