# Generated by Django 4.2.30 on 2026-09-17 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_solicitacaoservico_visita_concluida_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='visualizado_pelo_cliente',
            field=models.BooleanField(default=False, help_text='Marca se o cliente já abriu a tela deste orçamento, para controlar o aviso de "novo orçamento" no menu.', verbose_name='Visualizado pelo cliente'),
        ),
    ]
