# Generated by Django 6.1.1 on 2026-09-19 23:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_orcamento_visualizado_pelo_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='preco_max',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço da visita até (R$)'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='preco_min',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço da visita a partir de (R$)'),
        ),
    ]
