# Generated by Django 6.1.1 on 2026-09-19 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_alter_servico_preco_max_alter_servico_preco_min'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='disponivel',
        ),
    ]
