# Generated by Django 6.1.1 on 2026-09-21 23:45

import django.db.models.deletion
import services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_remove_servico_disponivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoservico',
            name='endereco_visita',
            field=models.CharField(blank=True, max_length=255, verbose_name='Endereço / ponto de referência da visita'),
        ),
        migrations.AddField(
            model_name='solicitacaoservico',
            name='grupo',
            field=models.UUIDField(blank=True, db_index=True, editable=False, help_text='Pedidos criados juntos, para vários profissionais ao mesmo tempo, dividem o mesmo grupo (usado na comparação).', null=True),
        ),
        migrations.AddField(
            model_name='solicitacaoservico',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude do local da visita'),
        ),
        migrations.AddField(
            model_name='solicitacaoservico',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude do local da visita'),
        ),
        migrations.AddField(
            model_name='solicitacaoservico',
            name='turno',
            field=models.CharField(choices=[('manha', 'Manhã (8h às 12h)'), ('tarde', 'Tarde (12h às 18h)'), ('noite', 'Noite (18h às 21h)'), ('qualquer', 'Qualquer horário')], default='qualquer', max_length=10, verbose_name='Turno preferido'),
        ),
        migrations.AddField(
            model_name='solicitacaoservico',
            name='urgente',
            field=models.BooleanField(default=False, help_text='O cliente precisa do atendimento hoje; o pedido aparece em destaque para o profissional.', verbose_name='Urgente (hoje)'),
        ),
        migrations.CreateModel(
            name='AnexoSolicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=services.models.caminho_anexo, verbose_name='Foto ou vídeo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='services.solicitacaoservico')),
            ],
            options={
                'verbose_name': 'Anexo da solicitação',
                'verbose_name_plural': 'Anexos da solicitação',
                'ordering': ['id'],
            },
        ),
    ]
