# Generated by Django 6.1.1 on 2026-09-22 00:17

import django.db.models.deletion
import services.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_solicitacao_turno_urgente_gps_anexos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='diavisitaorcamento',
            name='a_caminho_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Profissional avisou que está a caminho'),
        ),
        migrations.AddField(
            model_name='diavisitaorcamento',
            name='reagendamentos',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Reagendamentos aceitos'),
        ),
        migrations.AddField(
            model_name='diavisitaorcamento',
            name='status',
            field=models.CharField(choices=[('proposta', 'Proposta (aguardando aprovação do orçamento)'), ('agendada', 'Agendada'), ('cancelada', 'Cancelada')], default='proposta', max_length=10),
        ),
        migrations.AddField(
            model_name='diavisitaorcamento',
            name='turno',
            field=models.CharField(choices=[('manha', 'Manhã (8h às 12h)'), ('tarde', 'Tarde (12h às 18h)'), ('noite', 'Noite (18h às 21h)'), ('qualquer', 'Qualquer horário')], default='qualquer', max_length=10, verbose_name='Turno'),
        ),
        migrations.AddField(
            model_name='mensagemsolicitacao',
            name='anexo',
            field=models.FileField(blank=True, upload_to=services.models.caminho_chat, verbose_name='Foto ou áudio'),
        ),
        migrations.AddField(
            model_name='mensagemsolicitacao',
            name='tipo',
            field=models.CharField(choices=[('texto', 'Texto'), ('imagem', 'Foto'), ('audio', 'Áudio')], default='texto', max_length=10),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='motivo_recusa',
            field=models.TextField(blank=True, verbose_name='Motivo da recusa'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='respondido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='status',
            field=models.CharField(choices=[('pendente', 'Aguardando aprovação'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado')], default='pendente', max_length=10),
        ),
        migrations.AddField(
            model_name='solicitacaoservico',
            name='a_caminho_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Profissional avisou que está a caminho (1ª visita)'),
        ),
        migrations.AddField(
            model_name='solicitacaoservico',
            name='cancelado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cancelado em'),
        ),
        migrations.AddField(
            model_name='solicitacaoservico',
            name='cancelado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_canceladas', to=settings.AUTH_USER_MODEL, verbose_name='Cancelado por'),
        ),
        migrations.AddField(
            model_name='solicitacaoservico',
            name='cancelamento_tardio',
            field=models.BooleanField(default=False, help_text='Cancelado com menos antecedência do que a regra permite (ver services/regras.py).', verbose_name='Cancelamento tardio'),
        ),
        migrations.AddField(
            model_name='solicitacaoservico',
            name='motivo_cancelamento',
            field=models.TextField(blank=True, verbose_name='Motivo do cancelamento'),
        ),
        migrations.AddField(
            model_name='solicitacaoservico',
            name='reagendamentos',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Reagendamentos aceitos (1ª visita)'),
        ),
        migrations.AlterField(
            model_name='mensagemsolicitacao',
            name='texto',
            field=models.TextField(blank=True, verbose_name='Mensagem'),
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='geral', max_length=30)),
                ('titulo', models.CharField(max_length=120)),
                ('texto', models.CharField(blank=True, max_length=255)),
                ('url', models.CharField(blank=True, max_length=255)),
                ('chave', models.CharField(blank=True, db_index=True, help_text='Evita avisos repetidos (ex.: lembrete da mesma visita).', max_length=120)),
                ('lida', models.BooleanField(default=False)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provedor', models.CharField(default='simulado', max_length=20)),
                ('id_externo', models.CharField(blank=True, db_index=True, max_length=100)),
                ('status', models.CharField(choices=[('pendente', 'Aguardando pagamento do Pix'), ('retido', 'Pago - retido até a conclusão do serviço'), ('liberado', 'Repassado ao profissional'), ('reembolsado', 'Reembolsado ao cliente'), ('expirado', 'Pix expirado')], default='pendente', max_length=12)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comissao_percentual', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor_comissao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_profissional', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pix_copia_cola', models.TextField(blank=True)),
                ('pix_qrcode_base64', models.TextField(blank=True, help_text='Imagem PNG do QR Code, em base64.')),
                ('expira_em', models.DateTimeField(blank=True, null=True)),
                ('pago_em', models.DateTimeField(blank=True, null=True)),
                ('liberado_em', models.DateTimeField(blank=True, null=True)),
                ('reembolsado_em', models.DateTimeField(blank=True, null=True)),
                ('id_repasse', models.CharField(blank=True, max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('orcamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos', to='services.orcamento')),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='services.solicitacaoservico')),
            ],
            options={
                'verbose_name': 'Pagamento (Pix)',
                'verbose_name_plural': 'Pagamentos (Pix)',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='PropostaReagendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nova_data', models.DateField()),
                ('novo_turno', models.CharField(choices=[('manha', 'Manhã (8h às 12h)'), ('tarde', 'Tarde (12h às 18h)'), ('noite', 'Noite (18h às 21h)'), ('qualquer', 'Qualquer horário')], default='qualquer', max_length=10)),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('data_anterior', models.DateField()),
                ('turno_anterior', models.CharField(default='qualquer', max_length=10)),
                ('status', models.CharField(choices=[('pendente', 'Aguardando resposta'), ('aceita', 'Aceita'), ('recusada', 'Recusada'), ('cancelada', 'Cancelada')], default='pendente', max_length=10)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('respondida_em', models.DateTimeField(blank=True, null=True)),
                ('dia_visita', models.ForeignKey(blank=True, help_text='Vazio = reagendamento da primeira visita (dia pedido na solicitação).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propostas_reagendamento', to='services.diavisitaorcamento')),
                ('proposto_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reagendamentos_propostos', to=settings.AUTH_USER_MODEL)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas_reagendamento', to='services.solicitacaoservico')),
            ],
            options={
                'verbose_name': 'Proposta de reagendamento',
                'verbose_name_plural': 'Propostas de reagendamento',
                'ordering': ['-criada_em'],
            },
        ),
    ]
