# Generated by Django 6.1.1 on 2026-09-22 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_fluxo_orcamento_chat_pix'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='resposta_vista_pelo_profissional',
            field=models.BooleanField(default=True),
        ),
    ]
