# Generated by Django 6.1.1 on 2026-09-22 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils.text import slugify


def preencher_slugs(apps, schema_editor):
    """Gera o slug (ex.: eletricista-joao-silva-12) para os serviços já
    cadastrados antes deste campo existir - precisa rodar ANTES do campo
    virar unique=True, senão vários registros com slug='' quebrariam a
    restrição de unicidade."""
    Servico = apps.get_model('services', 'Servico')
    CATALOGO_SERVICOS = {}
    try:
        from services.catalogo import CATALOGO_SERVICOS as CATALOGO
        CATALOGO_SERVICOS = CATALOGO
    except ImportError:
        pass
    for servico in Servico.objects.select_related('categoria', 'profissional'):
        profissao = CATALOGO_SERVICOS.get(servico.categoria.slug, {}).get('servico') or servico.categoria.nome
        prof = servico.profissional
        nome_profissional = f'{prof.first_name} {prof.last_name}'.strip() or prof.username
        base = slugify(f'{profissao} {nome_profissional}') or 'servico'
        servico.slug = f'{base}-{servico.pk}'
        servico.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_orcamento_resposta_vista'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='foto_resposta',
            field=models.FileField(blank=True, help_text='Foto do resultado do trabalho, anexada pelo profissional junto com a resposta.', upload_to='fotos_servico_concluido/', verbose_name='Foto do serviço concluído'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='resposta_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Respondido em'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='resposta_profissional',
            field=models.TextField(blank=True, verbose_name='Resposta do profissional'),
        ),
        migrations.AddField(
            model_name='servico',
            name='slug',
            field=models.SlugField(blank=True, help_text='Gerado sozinho (ex.: eletricista-joao-silva-12) - usado na URL da página do serviço.', max_length=180, default=''),
            preserve_default=False,
        ),
        migrations.RunPython(preencher_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='servico',
            name='slug',
            field=models.SlugField(blank=True, help_text='Gerado sozinho (ex.: eletricista-joao-silva-12) - usado na URL da página do serviço.', max_length=180, unique=True),
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritado_por', to='services.servico')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorito',
                'verbose_name_plural': 'Favoritos',
                'ordering': ['-criado_em'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'servico'), name='favorito_unico_por_usuario')],
            },
        ),
    ]
