# Generated by Django 6.1.1 on 2026-09-23 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_slug_resposta_favorito'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoservico',
            name='respondida_em',
            field=models.DateTimeField(blank=True, help_text='Quando o profissional aceitou ou recusou o pedido (base do tempo de resposta do perfil).', null=True, verbose_name='Respondida pelo profissional em'),
        ),
    ]
