# Generated by Django 4.2.30 on 2026-09-02 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='profile',
            name='numero',
            field=models.CharField(blank=True, max_length=10, verbose_name='Número'),
        ),
    ]
