# Generated by Django 4.2.30 on 2026-09-03 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_complemento_profile_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='foto',
            field=models.FileField(blank=True, upload_to='fotos_perfil/', verbose_name='Foto de perfil'),
        ),
    ]
