# Generated by Django 4.2.30 on 2026-09-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_cep_latitude_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='termos_aceitos',
            field=models.BooleanField(default=False, help_text='Indica se o usuário já leu e aceitou o Termo de Condições de Uso e Prestação de Serviços.', verbose_name='Termo de Condições de Uso aceito'),
        ),
        migrations.AddField(
            model_name='profile',
            name='termos_aceitos_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/hora do aceite do Termo'),
        ),
    ]
