# Generated by Django 6.1.1 on 2026-09-18 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_termos_aceitos_profile_termos_aceitos_em'),
        ('services', '0013_orcamento_visualizado_pelo_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='especialidade',
        ),
        migrations.AddField(
            model_name='profile',
            name='especialidades',
            field=models.ManyToManyField(blank=True, help_text='Preenchido apenas para contas de profissionais. Um profissional pode atuar em mais de uma área.', related_name='profissionais', to='services.categoriaservico', verbose_name='Especialidades/Áreas de atuação'),
        ),
    ]
