# Generated by Django 6.1.1 on 2026-09-22 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_profile_especialidade_profile_especialidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='chave_pix',
            field=models.CharField(blank=True, help_text='Só para profissionais: chave (CPF, e-mail, telefone ou aleatória) onde o IFIX repassa o valor dos serviços concluídos.', max_length=140, verbose_name='Chave Pix para receber'),
        ),
    ]
