# Generated by Django 6.1.1 on 2026-09-22 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_fluxo_orcamento_chat_pix'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bairro',
            field=models.CharField(blank=True, max_length=120, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='profile',
            name='cidade',
            field=models.CharField(blank=True, max_length=120, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='profile',
            name='cidade_slug',
            field=models.SlugField(blank=True, help_text='Gerado sozinho a partir da cidade - usado nas páginas "Eletricista em Campinas".', max_length=140),
        ),
        migrations.AddField(
            model_name='profile',
            name='uf',
            field=models.CharField(blank=True, max_length=2, verbose_name='UF'),
        ),
    ]
