# Generated by Django 6.1.1 on 2026-09-23 23:21

import accounts.models
import accounts.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_cidade_bairro_uf'),
        ('services', '0020_solicitacaoservico_respondida_em'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='documento',
            field=models.FileField(blank=True, storage=accounts.storage.armazenamento_privado, upload_to=accounts.models.caminho_verificacao, verbose_name='Documento com foto (RG/CNH)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='foto_verificacao',
            field=models.FileField(blank=True, storage=accounts.storage.armazenamento_privado, upload_to=accounts.models.caminho_verificacao, verbose_name='Foto do rosto (selfie)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='site_url',
            field=models.URLField(blank=True, help_text='Só profissionais. Aparece na sua página pública (ex.: https://meusite.com.br).', verbose_name='Link da sua página/site (opcional)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='verificacao_enviada_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Enviado em'),
        ),
        migrations.AddField(
            model_name='profile',
            name='verificacao_motivo_recusa',
            field=models.TextField(blank=True, verbose_name='Motivo da recusa'),
        ),
        migrations.AddField(
            model_name='profile',
            name='verificacao_status',
            field=models.CharField(choices=[('nao_enviado', 'Não enviado'), ('pendente', 'Aguardando análise'), ('verificado', 'Verificado'), ('recusado', 'Recusado')], default='nao_enviado', max_length=12, verbose_name='Situação da verificação'),
        ),
        migrations.AddField(
            model_name='profile',
            name='verificado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Verificado em'),
        ),
        migrations.AddField(
            model_name='profile',
            name='verificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verificacoes_feitas', to=settings.AUTH_USER_MODEL, verbose_name='Verificado por'),
        ),
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('golpe', 'Golpe ou fraude'), ('comportamento', 'Comportamento ofensivo ou assédio'), ('nao_realizado', 'Serviço não realizado / não compareceu'), ('perfil_falso', 'Perfil falso'), ('spam', 'Spam ou propaganda'), ('outro', 'Outro')], max_length=15)),
                ('descricao', models.TextField(max_length=2000, verbose_name='O que aconteceu')),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('em_analise', 'Em análise'), ('resolvida', 'Resolvida'), ('arquivada', 'Arquivada')], default='aberta', max_length=10)),
                ('observacao_equipe', models.TextField(blank=True, verbose_name='Observações da equipe (internas)')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('resolvida_em', models.DateTimeField(blank=True, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denuncias_feitas', to=settings.AUTH_USER_MODEL, verbose_name='Denunciante')),
                ('denunciado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denuncias_recebidas', to=settings.AUTH_USER_MODEL, verbose_name='Denunciado')),
                ('solicitacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='denuncias', to='services.solicitacaoservico', verbose_name='Solicitação relacionada')),
            ],
            options={
                'verbose_name': 'Denúncia',
                'verbose_name_plural': 'Denúncias',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='Bloqueio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('bloqueado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueios_recebidos', to=settings.AUTH_USER_MODEL)),
                ('bloqueador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueios_feitos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bloqueio entre usuários',
                'verbose_name_plural': 'Bloqueios entre usuários',
                'constraints': [models.UniqueConstraint(fields=('bloqueador', 'bloqueado'), name='bloqueio_unico')],
            },
        ),
    ]
