# Catálogo fixo de Categoria -> Serviço -> Subserviços (+ Observação padrão),
# usado no formulário "Adicionar serviço" do painel profissional.
#
# A chave de cada entrada é o slug da CategoriaServico correspondente
# (ver services/migrations/0002_categorias_iniciais.py e
# 0008_renomear_desentupimento_para_pintura.py), para que o formulário
# consiga filtrar "Nome do serviço" e "Subserviço" de acordo com a
# categoria escolhida.
#
# Alguns subserviços trazem 'grupo': o formulário organiza esses itens em
# grupos (<optgroup>) no <select> de Subserviço, para o profissional achar
# a opção certa mesmo quando a categoria tem muitos itens (caso de
# Elétrica), em vez de uma lista enorme e solta na tela.

# Subserviços de Elétrica agrupados por área de atuação, para não virarem
# uma lista única gigante no formulário.
_GRUPOS_ELETRICA = {
    'Instalações novas': [
        'Projeto elétrico completo (cargas, diagramas, memorial)',
        'Instalação elétrica de imóvel novo ou reforma total',
        'Instalação de quadro de distribuição (QDC) e disjuntores',
        'Instalação de padrão de entrada e medidor',
        'Passagem de eletrodutos, fiação e cabeamento',
        'Ampliação de carga e troca de bitola de fios',
        'Instalação de circuitos independentes (chuveiro, forno, ar-condicionado)',
    ],
    'Pontos de energia': [
        'Instalação e troca de tomadas (comuns, 20A, USB, com aterramento)',
        'Instalação e troca de interruptores (simples, paralelo, intermediário, dimmer)',
        'Novos pontos de tomada ou de luz',
        'Instalação de tomadas para carro elétrico (wallbox)',
        'Tomadas externas, para jardim ou área gourmet',
    ],
    'Iluminação': [
        'Instalação e troca de lâmpadas e luminárias',
        'Instalação de lustres e pendentes',
        'Iluminação de LED (fitas, perfis, spots, embutidos, trilhos)',
        'Iluminação de jardim, fachada e garagem',
        'Sensores de presença e fotocélulas',
        'Iluminação de emergência',
        'Projeto luminotécnico',
        'Iluminação cênica e decorativa',
    ],
    'Manutenção e reparos': [
        'Correção de curto-circuito',
        'Correção de fuga de corrente',
        'Troca de disjuntores, DRs e DPS',
        'Reparo de tomadas e interruptores com mau contato',
        'Identificação e correção de fios sobreaquecidos',
        'Troca de fiação antiga (alumínio, sem aterramento)',
        'Reparo de quedas de energia parciais',
        'Resolução de choques em torneiras, chuveiros e geladeiras',
        'Manutenção preventiva do quadro elétrico',
    ],
    'Instalação de equipamentos': [
        'Chuveiro e torneira elétrica',
        'Aquecedor de passagem ou boiler elétrico',
        'Ar-condicionado (parte elétrica)',
        'Ventilador de teto e exaustor',
        'Forno elétrico e cooktop',
        'Máquina de lavar, secadora e lava-louças',
        "Bomba d'água, pressurizador e bomba de piscina",
        'Portão eletrônico',
        'Motor de cortina e persiana',
    ],
    'Segurança elétrica': [
        'Instalação de aterramento',
        'Instalação de DR (diferencial residual)',
        'Instalação de DPS (proteção contra surtos)',
        'Instalação de para-raios (SPDA)',
        'Laudo técnico e inspeção elétrica (NBR 5410)',
        'ART/RRT de responsável técnico',
        'Termografia do quadro e das conexões',
        'Medição de resistência do aterramento',
    ],
    'Automação e tecnologia': [
        'Automação residencial (luzes, cortinas, cenas)',
        'Instalação de interruptores e tomadas inteligentes (Wi-Fi, Zigbee)',
        'Integração com assistentes de voz',
        'Instalação de vídeo porteiro e interfone',
        'Instalação de câmeras de segurança (CFTV)',
        'Alarmes, sensores e cerca elétrica',
        'Fechaduras eletrônicas e controle de acesso',
        'Cabeamento de rede, internet e TV',
        'Instalação de antena e rack',
    ],
    'Energia alternativa e eficiência': [
        'Instalação de painéis solares (energia fotovoltaica)',
        'Projeto e homologação junto à concessionária',
        'Instalação de inversores e baterias',
        'Instalação de nobreak e estabilizador',
        'Instalação de gerador',
        'Auditoria de consumo energético',
        'Troca de iluminação para LED (economia)',
    ],
    'Serviços de emergência e outros': [
        'Atendimento 24 horas',
        'Falta de energia total ou parcial',
        'Cheiro de queimado, faíscas ou fumaça',
        'Religação e regularização junto à concessionária',
        'Mudança de tensão (110V ↔ 220V)',
        'Adequação elétrica para venda ou locação',
        'Regularização para o corpo de bombeiros (AVCB)',
        'Desmontagem e remontagem elétrica em mudanças',
    ],
    'Específico para apartamentos': [
        'Adequação do quadro do apartamento',
        'Passagem de fiação em forro de gesso e shafts',
        'Infraestrutura para ar-condicionado split',
        'Adequação às regras do condomínio (laudos e ART)',
        'Instalação de tomada para carro elétrico na vaga (com autorização do condomínio)',
    ],
}

# Subserviços de Hidráulica agrupados por área de atuação, no mesmo
# esquema usado em Elétrica (ver _GRUPOS_ELETRICA acima).
_GRUPOS_HIDRAULICA = {
    'Instalações novas': [
        'Projeto hidrossanitário completo (água fria, quente, esgoto, pluvial)',
        'Instalação de tubulação de água fria e quente (PVC, CPVC, PPR, PEX, cobre)',
        'Instalação de ramais de esgoto e ventilação',
        "Instalação de caixa d'água, cisterna e reservatórios",
        'Instalação de barrilete e distribuição',
        'Instalação de registros gerais e de pressão',
        'Ligação à rede da concessionária (cavalete, hidrômetro)',
        'Ligação à rede de esgoto ou fossa',
        'Infraestrutura hidráulica para reforma ou ampliação',
    ],
    'Vazamentos e infiltrações': [
        'Detecção de vazamento (geofone, termografia, gás traçador, câmera)',
        'Reparo de vazamento em parede, piso, laje e forro',
        'Vazamento em tubulação embutida',
        "Vazamento em caixa d'água, cisterna e piscina",
        'Infiltração em banheiro, box e área de serviço',
        'Vazamento em registro, torneira, sifão e flexível',
        'Reparo de cano estourado',
        'Teste de estanqueidade e pressão',
    ],
    'Entupimentos e esgoto': [
        'Desentupimento de pia, ralo, vaso, tanque e box',
        'Desentupimento de coluna de esgoto e ramal principal',
        'Desentupimento com máquina rotativa e hidrojateamento',
        'Videoinspeção de tubulação',
        'Limpeza e desentupimento de caixa de gordura',
        'Limpeza de caixa de inspeção e sifonada',
        'Limpeza de fossa séptica e sumidouro',
        'Desentupimento de calha e ralo pluvial',
        'Correção de mau cheiro e retorno de esgoto',
        'Reparo de tubulação de esgoto com contrainclinação',
    ],
    'Louças, metais e acabamentos': [
        'Instalação e troca de vaso sanitário (caixa acoplada, suspenso, com válvula)',
        'Instalação de pia, cuba, lavatório e tanque',
        'Instalação e troca de torneiras, misturadores e monocomandos',
        'Instalação de chuveiro, ducha higiênica e duchas embutidas',
        'Instalação de box e barra de apoio (parte hidráulica)',
        'Instalação de banheira, hidromassagem e ofurô',
        'Instalação de bidê e mictório',
        'Troca de sifões, flexíveis e engates',
        'Troca de reparos, boia, válvula de descarga e caixa acoplada',
        'Troca de registros e reparos de registro',
        'Instalação de ralos lineares e ralos sifonados',
    ],
    'Aquecimento de água': [
        'Instalação de aquecedor a gás (passagem e acumulação)',
        'Instalação de aquecedor elétrico e boiler',
        'Instalação de aquecimento solar',
        'Instalação de bomba de calor',
        'Instalação de sistema de recirculação de água quente',
        'Manutenção e limpeza de aquecedores',
        'Instalação de tubulação de gás (conexão ao aquecedor)',
        'Instalação de torneira e chuveiro elétrico (parte hidráulica)',
    ],
    "Caixa d'água, cisterna e pressão": [
        "Instalação e troca de caixa d'água (fibra, polietileno, concreto, metálica)",
        "Limpeza e desinfecção de caixa d'água",
        "Impermeabilização de caixa d'água e cisterna",
        'Instalação de boia e extravasor',
        "Instalação de bomba d'água e pressurizador",
        'Instalação de bomba de recalque e de poço',
        'Instalação de hidropneumático',
        "Correção de baixa pressão e falta d'água",
        'Instalação de válvula redutora de pressão',
        'Instalação de filtro, cloração e tratamento de água',
        'Instalação de sistema de automação de nível',
    ],
    'Água pluvial e drenagem': [
        'Instalação e manutenção de calhas e rufos',
        'Instalação de tubos de queda e condutores',
        'Ralos e grelhas pluviais',
        'Drenagem de quintal, jardim e garagem',
        'Drenagem de subsolo e parede de contenção',
        'Instalação de caixa de captação de água da chuva',
        'Sistema de reúso de água da chuva',
        'Poço de infiltração e vala de drenagem',
        'Bomba de drenagem e de esgoto (sump)',
    ],
    'Gás encanado e GLP': [
        'Instalação de tubulação de gás (natural e GLP)',
        'Instalação de ponto de gás para fogão, cooktop e forno',
        'Instalação de central de gás e botijão',
        'Teste de estanqueidade e detecção de vazamento de gás',
        'Instalação de registros e reguladores',
        'Adequação de gás para condomínio e concessionária',
        'Laudo de segurança de gás',
    ],
    'Piscinas, áreas externas e jardins': [
        'Instalação e manutenção de tubulação de piscina',
        'Instalação de motobomba, filtro e skimmer',
        'Instalação de cascata, hidromassagem e aquecimento de piscina',
        'Instalação de torneira de jardim e ponto de lavagem',
        'Irrigação automática (aspersores, gotejamento, timer)',
        'Instalação de chuveirão e lava-pés',
        "Instalação de fontes, espelhos d'água e chafarizes",
        'Instalação de sistema de água para churrasqueira e área gourmet',
    ],
    'Equipamentos e eletrodomésticos': [
        'Ponto hidráulico e esgoto de máquina de lavar roupa e louça',
        'Instalação de filtro, bebedouro e purificador',
        'Instalação de lava-louças e triturador de pia',
        'Instalação de osmose reversa',
        'Instalação de purificador de água e dessalinizador',
        'Ponto de água e dreno para ar-condicionado',
        'Instalação de geladeira com dispenser',
        'Instalação de máquina de gelo',
    ],
    'Sustentabilidade e eficiência': [
        'Instalação de reúso de água cinza',
        'Captação e aproveitamento de água da chuva',
        'Instalação de arejadores e economizadores',
        'Instalação de vaso com duplo acionamento',
        'Sensores de vazamento e válvula de fechamento automático',
        'Medição individualizada de água (apartamentos)',
        'Auditoria de consumo de água',
        'Instalação de sistema de água quente solar',
    ],
    'Segurança, laudos e adequações': [
        'Laudo de instalações hidráulicas',
        'Teste de pressão e estanqueidade',
        'Inspeção e adequação de prumadas',
        'Instalação de sistema de hidrantes e mangotinhos',
        'Adequação para AVCB e normas do condomínio',
        'Regularização junto à concessionária',
        'Substituição de tubulação antiga (ferro galvanizado, chumbo)',
        'Adequação às normas ABNT NBR 5626 e 8160',
    ],
    'Emergência e manutenção': [
        'Atendimento 24 horas',
        'Vazamento grande, cano estourado e inundação',
        'Retorno de esgoto e transbordamento',
        'Falta total de água',
        'Manutenção preventiva programada',
        'Revisão geral de casa ou apartamento',
        'Manutenção para venda, locação ou entrega de imóvel',
    ],
}

# Subserviços de Marcenaria agrupados por área de atuação, no mesmo
# esquema usado em Elétrica e Hidráulica (ver _GRUPOS_ELETRICA acima).
_GRUPOS_MARCENARIA = {
    'Móveis planejados sob medida': [
        'Cozinha planejada (armários, balcões, ilhas, bancadas de apoio)',
        'Dormitório planejado (guarda-roupa, closet, cabeceira, criado-mudo, cômoda)',
        'Quarto infantil e juvenil (camas, beliches, camas com nicho, escrivaninhas)',
        'Sala de estar (painel de TV, rack, estante, aparador, bar)',
        'Sala de jantar (buffet, cristaleira, adega)',
        'Home office (bancada, estante, armário, nichos)',
        'Banheiro e lavabo (gabinete, armário, nicho, prateleiras)',
        'Área de serviço e lavanderia (armários, bancada, tanque embutido)',
        'Closet completo (prateleiras, gavetas, sapateiras, ilhas, espelheiras)',
        'Despensa e área gourmet',
        'Varanda e área externa (bancos, armários, bancada de churrasqueira)',
        'Escritório e biblioteca',
        'Quarto de hóspedes e pet (cama, casinha e nicho para pet)',
    ],
    'Móveis avulsos e sob encomenda': [
        'Mesas (jantar, centro, lateral, escritório, dobrável)',
        'Cadeiras, banquetas e bancos',
        'Camas (box, madeira maciça, baú, sofá-cama)',
        'Sofás e poltronas (estrutura em madeira)',
        'Aparadores, buffets e cômodas',
        'Estantes, prateleiras e nichos',
        'Racks e painéis de TV',
        'Sapateiras e cabideiros',
        'Bancadas e balcões',
        'Móveis de madeira maciça, rústicos e de demolição',
        'Móveis sob desenho do cliente e réplicas',
        'Berços, cômodas e trocadores',
        'Móveis para pet (casinhas, camas, bebedouros elevados)',
    ],
    'Portas, janelas e esquadrias': [
        'Portas internas e externas (madeira maciça, MDF, semi-oca, pivotante)',
        'Portas de correr e portas de abrir',
        'Portas de correr embutidas na parede (porta de cavidade)',
        'Portas de vidro com estrutura de madeira',
        'Portas de entrada e portais',
        'Janelas de madeira (guilhotina, maxim-ar, veneziana)',
        'Venezianas e persianas de madeira',
        'Batentes, guarnições, alizares e soleiras',
        'Portas de armário, de closet e de despensa',
        'Painéis ripados e divisórias',
        'Cobogós e treliças de madeira',
    ],
    'Revestimentos e acabamentos em madeira': [
        'Instalação de piso de madeira (assoalho, tacos, deck, parquet, taco em espinha de peixe)',
        'Piso laminado e vinílico (instalação)',
        'Rodapés, molduras e guarnições',
        'Forros de madeira e de PVC',
        'Painéis ripados, revestimentos de parede e boiseries',
        'Lambris e revestimentos 3D',
        'Revestimento de escadas (degraus, espelhos, corrimãos)',
        'Tetos rebaixados em madeira e sancas',
        'Sancas, cortineiros e caixas para iluminação',
        'Pergolados, brises e tabuados',
        'Aplicação de laminados e folhas de madeira (lâminas)',
    ],
    'Escadas, decks e áreas externas': [
        'Escadas de madeira (reta, em L, em U, caracol, com degraus flutuantes)',
        'Corrimãos e guarda-corpos de madeira',
        'Decks de madeira e de WPC (piscina, varanda, jardim)',
        'Pergolados, gazebos e caramanchões',
        'Cobertura de madeira para churrasqueira e garagem',
        'Cercas, portões e muros de madeira',
        'Bancos, floreiras e jardineiras de madeira',
        'Casinhas para pet, de brinquedo e de ferramentas',
        'Playground e brinquedos de madeira',
        'Móveis de jardim e para área externa',
        'Deques flutuantes e passarelas',
    ],
    'Estruturas e telhados': [
        'Estruturas de madeira para telhado (tesouras, caibros, ripas, terças)',
        'Instalação de telhado de madeira e reforma de madeiramento',
        'Cobertura de madeira para varanda e edícula',
        'Estruturas de mezanino e jirau',
        'Vigas aparentes e pilares de madeira',
        'Casas e chalés de madeira, wood frame e steel frame com acabamento',
        'Reforço estrutural em madeira',
    ],
    'Conserto e restauração': [
        'Conserto de móveis (gavetas, portas, dobradiças, corrediças, trilhos)',
        'Restauração de móveis antigos e de família',
        'Reparo de piso de madeira (tacos soltos, arranhões, riscos)',
        'Reforma de portas e janelas empenadas ou emperradas',
        'Troca de puxadores, fechaduras e dobradiças',
        'Conserto de cadeiras, mesas e camas bambas',
        'Reparo de estofados (estrutura em madeira)',
        'Reforma de escadas, guarda-corpos e corrimãos',
        'Reparo em deck (troca de tábuas)',
        'Substituição de peças e de partes danificadas',
        'Reparo de danos por cupim, umidade e mofo',
        'Ajuste de portas e gavetas que empenaram',
    ],
    'Manutenção, tratamento e acabamento': [
        'Raspagem, lixamento e polimento de pisos (sinteco, bona, verniz)',
        'Aplicação de verniz, stain, cera, óleo e laca',
        'Pintura de móveis e portas (PU, laca, tinta esmalte)',
        'Pintura e envernizamento de decks e áreas externas',
        'Impermeabilização e proteção de madeira',
        'Tratamento contra cupins, brocas e fungos (dedetização e imunização)',
        'Manutenção preventiva de decks, pergolados e cercas',
        'Troca de ferragens, corrediças e dobradiças',
        'Limpeza e hidratação de madeira',
        'Ajuste e nivelamento de móveis e portas',
        'Manutenção periódica de móveis planejados (revisão de ferragens)',
    ],
    'Instalação e montagem': [
        'Montagem de móveis (prontos, de loja, de importados)',
        'Desmontagem e remontagem em mudanças',
        'Instalação de móveis planejados e de guarda-roupas',
        'Instalação de portas, batentes e fechaduras',
        'Instalação de painéis, ripados e revestimentos',
        'Instalação de prateleiras, nichos e suportes',
        'Instalação de cortineiros, trilhos e persianas',
        'Instalação de cabideiros, ganchos e espelhos',
        'Instalação de tampos (granito, quartzo, madeira, laminado)',
        'Instalação de eletrodomésticos embutidos',
        'Instalação de iluminação em móveis (LED em armários e nichos)',
        'Fixação de TV, suporte e painéis',
        'Instalação de camas, beliches e cabeceiras',
    ],
    'Ferragens e acessórios': [
        'Dobradiças, corrediças telescópicas e soft-close',
        'Sistema de porta de correr e de porta de giro',
        'Puxadores, trilhos e perfis',
        'Sistemas de organização interna (gaveteiros, sapateiras, cabideiros elevatórios)',
        'Fechaduras, travas e fechos',
        'Cantoneiras, suportes e mãos-francesas',
        'Amortecedores, pistões a gás e sistemas basculantes',
        'Iluminação embutida, tomadas e USB em móveis',
        'Espelhos e vidros em móveis',
        'Acessórios de cozinha (lixeiras embutidas, porta-temperos, cesto de canto, sistemas Le Mans)',
    ],
    'Projeto e consultoria': [
        'Projeto de marcenaria e de móveis planejados',
        'Projeto 3D e renderização',
        'Levantamento de medidas (medição técnica)',
        'Consultoria de materiais e acabamentos',
        'Orçamento e detalhamento técnico',
        'Acompanhamento de obra',
        'Adequação de móveis para pessoas com mobilidade reduzida',
        'Marcenaria acessível para idosos e crianças',
        'Projetos sustentáveis (madeira certificada e reaproveitada)',
    ],
    'Materiais e acabamentos': [
        'MDF e MDP (BP, laminado, fitas, texturizados, lacas)',
        'Madeira maciça (pinus, eucalipto, cumaru, ipê, freijó, jatobá, peroba, mogno)',
        'Madeira de demolição e reaproveitamento',
        'Compensados (naval, multilaminado, sarrafeado)',
        'Lâminas e folhas de madeira natural',
        'Laminados melamínicos e fórmica',
        'Vidro, espelho e acrílico combinados',
        'Pedras, quartzo e granitos em tampos',
        'Aço, inox, latão e ferro combinados com madeira',
        'Tecidos, couro e palhinha',
        'Acabamentos: laca, verniz, óleo, cera, stain, PU, patina, envelhecido, pintura texturizada',
    ],
    'Emergência e atendimento rápido': [
        'Conserto urgente de porta, fechadura ou janela',
        'Reparo emergencial de móveis e escadas',
        'Conserto de danos causados por vazamento ou umidade',
        'Troca de ferragens danificadas',
        'Atendimento para mudanças (montagem e desmontagem rápida)',
        'Manutenção em imóveis para venda ou locação',
    ],
}

# Subserviços de Pintura agrupados por área de atuação, no mesmo esquema
# usado em Elétrica, Hidráulica e Marcenaria (ver _GRUPOS_ELETRICA acima).
_GRUPOS_PINTURA = {
    'Pintura interna': [
        'Pintura de paredes (sala, quartos, cozinha, banheiro, corredores, hall)',
        'Pintura de tetos e forros (gesso, laje, madeira, PVC)',
        'Pintura de sancas, molduras, rodapés e guarnições',
        'Pintura de portas, batentes e janelas internas',
        'Pintura de armários, rodas de meio e nichos',
        'Pintura de escadas e corrimãos internos',
        'Pintura de closets, despensas e áreas de serviço',
        'Repintura para venda, locação ou entrega de imóvel',
        'Pintura de apartamento completo (obra ou mudança)',
    ],
    'Pintura externa': [
        'Pintura de fachadas, muros e platibandas',
        'Pintura de empenas e paredes laterais',
        'Pintura de portões, grades e gradis',
        'Pintura de portas e janelas externas',
        'Pintura de varandas, sacadas e áreas externas',
        'Pintura de garagens e áreas de circulação',
        'Pintura de telhados, calhas, rufos e telhas',
        "Pintura de caixas d'água, muros de arrimo e chaminés",
        'Pintura de pisos externos, calçadas e quintais',
        'Pintura de churrasqueiras e áreas gourmet',
    ],
    'Preparação e reparo de superfícies': [
        'Raspagem e remoção de tinta velha',
        'Lixamento de paredes, tetos e madeiras',
        'Remoção de papel de parede, textura ou grafiato',
        'Tratamento de mofo, bolor e umidade',
        'Tratamento de manchas (gordura, fumaça, ferrugem, infiltração)',
        'Correção de trincas, fissuras e rachaduras',
        'Reparo de buracos, fixações e rasgos de parede',
        'Aplicação de massa corrida e massa acrílica',
        'Aplicação de selador, fundo preparador e fixador',
        'Regularização de paredes e tetos (nivelamento)',
        'Reparo de reboco e gesso antes da pintura',
        'Limpeza e lavagem de fachadas antes da pintura',
    ],
    'Efeitos decorativos e texturas': [
        'Textura lisa, rústica, grafiato e projetada',
        'Efeito cimento queimado',
        'Efeito concreto aparente e microcimento',
        'Efeito marmorato e veneziano',
        'Efeito tinta com brilho (stucco)',
        'Efeito velatura, esponjado, patina e envelhecido',
        'Efeito com stencil, rolos texturizados e grafismos',
        'Efeito seda, veludo e metalizado',
        'Efeito lousa (parede de giz) e magnético',
        'Efeito tijolinho, pedra e madeira pintada',
        'Acabamento em tinta perolada e cintilante',
    ],
    'Pintura de madeira, metal e outros materiais': [
        'Pintura e envernizamento de portas e janelas de madeira',
        'Pintura de móveis (esmalte, laca, PU, tinta epóxi)',
        'Verniz, stain e polimento em madeira',
        'Pintura de deck, pergolado e cercas de madeira',
        'Pintura e proteção de ferro (antiferrugem, esmalte sintético)',
        'Pintura de alumínio, esquadrias e grades',
        'Pintura de galvanizado, zinco e telhas metálicas',
        'Pintura de azulejos, pisos cerâmicos e revestimentos',
        'Pintura de bancadas, louças e box de banheiro (renovação)',
        'Pintura de geladeiras, eletrodomésticos e utensílios',
        'Pintura de gesso, drywall, cimento e concreto',
        'Pintura de rodapés e frisos de gesso',
    ],
    'Impermeabilização e proteção': [
        'Impermeabilização de lajes, terraços e coberturas',
        'Impermeabilização de banheiros, áreas de serviço e varandas',
        'Impermeabilização de paredes externas (hidrofugante, resina)',
        "Impermeabilização de piscinas, caixas d'água e cisternas",
        'Aplicação de resina acrílica e verniz de proteção',
        'Pintura térmica e antimofo',
        'Tintas antichama, antifungos e antibacterianas',
        'Tintas de alta durabilidade e autolimpantes',
        'Proteção contra sol, chuva e maresia',
        'Aplicação de manta líquida e manta asfáltica',
        'Aplicação de resinas epóxi em pisos e bancadas',
    ],
    'Papel de parede e revestimentos decorativos': [
        'Instalação de papel de parede (vinílico, TNT, lavável, texturizado)',
        'Remoção de papel de parede',
        'Instalação de adesivos, vinis e murais decorativos',
        'Instalação de tecidos e revestimentos de parede',
        'Instalação de painéis, boiseries e molduras decorativas',
        'Instalação de revestimentos 3D, ripados e cimentícios',
        'Aplicação de papel de parede em teto, nicho e cabeceira',
        'Aplicação de fotomurais e adesivos personalizados',
        'Pintura combinada com papel de parede e molduras',
    ],
    'Pintura artística e personalizada': [
        'Murais e grafites decorativos',
        'Pintura artística infantil (personagens, animais, jogos)',
        'Pintura de painéis e paisagens',
        'Pintura de lettering e frases decorativas',
        'Pintura de faixas, geométricos e degradês',
        'Pintura de degradê (ombré) e listras',
        'Pintura de portas e detalhes coloridos',
        'Pintura de logos e identidade visual (home office)',
        'Pintura de cenários, tetos e céu estrelado',
        'Pintura de marcação de jogos (amarelinha, quadra, campo)',
        'Pintura de faixas e sinalização de garagem',
    ],
    'Restauração e conservação': [
        'Restauro de pintura antiga ou histórica',
        'Restauro de fachadas, molduras e ornamentos',
        'Recuperação de pintura desbotada, descascada ou manchada',
        'Recuperação de portões, grades e ferragens enferrujadas',
        'Recuperação de madeira (decks, portas e móveis)',
        'Recuperação de azulejos e revestimentos',
        'Recuperação de tetos e paredes com infiltração',
        'Repintura de áreas comuns e de condomínios',
        'Repintura de fachadas de prédios e casas antigas',
        'Renovação de pintura de imóveis para locação',
    ],
    'Manutenção e retoques': [
        'Retoque de pintura (manchas, arranhões, riscos, marcas)',
        'Retoque pós-obra ou pós-mudança',
        'Manutenção preventiva de pintura externa',
        'Revisão periódica de fachadas e paredes',
        'Repintura parcial (uma parede, um cômodo, um teto)',
        'Limpeza e lavagem de paredes, tetos e fachadas',
        'Lavagem com hidrojateamento',
        'Limpeza pós-obra (remoção de respingos e resíduos)',
        'Contrato de manutenção periódica',
    ],
    'Pisos, garagens e áreas especiais': [
        'Pintura de piso de cimento queimado, garagens e quintais',
        'Pintura de piso com tinta epóxi ou poliuretano',
        'Pintura de piso de cerâmica e porcelanato',
        'Pintura de rampas, escadas externas e passarelas',
        'Pintura de faixas de estacionamento e demarcações',
        'Pintura de áreas molhadas (banheiros, lavanderias, piscinas)',
        'Pintura de churrasqueiras e lareiras (tinta refratária)',
        'Pintura de quadras e playgrounds',
    ],
    'Projeto, consultoria e orçamento': [
        'Consultoria de cores e paletas',
        'Projeto de cores e acabamentos (3D e simulações)',
        'Levantamento de metragem e orçamento',
        'Consultoria de materiais e tintas (marcas, tipos, rendimento)',
        'Fornecimento de tintas e materiais',
        'Indicação de tintas sustentáveis e de baixo VOC',
        'Acompanhamento de obra e cronograma',
        'Laudo de pintura e diagnóstico de patologias',
        'Consultoria para pintura de fachada de condomínio',
    ],
    'Serviços com equipamentos especiais': [
        'Pintura com pistola (airless) e compressor',
        'Pintura com rolo, pincel e trincha',
        'Pintura em altura (andaime, balancim, cadeirinha)',
        'Pintura por rapel ou trabalho em altura',
        'Pintura de fachadas de prédios altos',
        'Pintura eletrostática e em pó',
        'Jateamento de areia, granalha e hidrojateamento',
        'Aplicação de tinta com drone em fachadas altas',
    ],
    'Emergência e atendimento rápido': [
        'Pintura urgente para venda, locação ou entrega de chaves',
        'Repintura rápida antes de mudanças',
        'Retoque emergencial pós-vazamento, incêndio ou fumaça',
        'Pintura de imóvel em poucos dias (equipe reforçada)',
        'Cobertura de pichações e vandalismo',
        'Correção de erros de cor, manchas e defeitos de aplicação',
    ],
}


CATALOGO_SERVICOS = {
    'eletrica': {
        'servico': 'Eletricista',
        'subservicos': [
            {'nome': item, 'observacao': grupo, 'grupo': grupo}
            for grupo, itens in _GRUPOS_ELETRICA.items()
            for item in itens
        ],
    },
    'hidraulica': {
        'servico': 'Encanador',
        'subservicos': [
            {'nome': item, 'observacao': grupo, 'grupo': grupo}
            for grupo, itens in _GRUPOS_HIDRAULICA.items()
            for item in itens
        ],
    },
    'pintura': {
        'servico': 'Pintor',
        'subservicos': [
            {'nome': item, 'observacao': grupo, 'grupo': grupo}
            for grupo, itens in _GRUPOS_PINTURA.items()
            for item in itens
        ],
    },
    'marcenaria': {
        'servico': 'Marceneiro',
        'subservicos': [
            {'nome': item, 'observacao': grupo, 'grupo': grupo}
            for grupo, itens in _GRUPOS_MARCENARIA.items()
            for item in itens
        ],
    },
}


def slug_por_servico(nome_servico):
    """Retorna o slug de categoria dono do 'Serviço' informado (ex.: 'Eletricista' -> 'eletrica')."""
    for slug, dados in CATALOGO_SERVICOS.items():
        if dados['servico'] == nome_servico:
            return slug
    return None


def subservico_valido(slug_categoria, nome_subservico):
    """Confere se o subserviço pertence à categoria informada e devolve sua Observação padrão."""
    dados = CATALOGO_SERVICOS.get(slug_categoria)
    if not dados:
        return False, None
    for sub in dados['subservicos']:
        if sub['nome'] == nome_subservico:
            return True, sub['observacao']
    return False, None
